version: 1
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: ext://Logger.logfile
    level: INFO
    encoding: utf-8
    when: D
    interval: 1
    backupCount: 7
root:
  level: DEBUG
  handlers: [ console, file ]
loggers:
  PIL.PngImagePlugin:
    propagate: false
formatters:
  precise:
    format: '%(asctime)s ! %(funcName)s @ %(filename)s:%(lineno)d ! %(levelname)s ! %(message)s'
    datefmt: ''
  console:
    format: '[%(levelname)s]   ||  %(message)s'
